name: Pipeline aula 03 - Branch dev
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs: 

  security:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
        
      - name: Instalar dependências
        run: npm install

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2

  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Análise com SonarCloud 
        uses: SonarSource/sonarcloud-github-action@v2 
        with: 
          args: > 
            -Dsonar.projectKey=AliceLSP_Pipeline_aula02
            -Dsonar.organization=alicelsp 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Rodar lint
        run: npm run lint

      - name: Rodar coverage
        run: npm run test

  build: 
    runs-on: ubuntu-latest
    needs: security

    steps: 
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm ci

  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm ci

      - name: Run Jest
        run: npm test